### ISSUE TITLE
No Issue but Code Further optimization

### ISSUE THREAD

**Issue by imran87** [sgr-ksmt/Alertift#10]
First of all well done a very good and complete written wrapper for UIAlert Controller. So my point is that when a user call action sheet on iPhone or iPad so your code should  automattically set popover if device is a iPad so there is no need of user decision.

**Comment by sgr-ksmt** [comment]
@imran87 Thx for reporting issue. 
But, popover's `sourceView` is automatically ignored in case of iPhone. So I think there is no need for the user to judge iPhone or iPad.
Just in case, I will add some implementations so that the application won't crash if popover's `sourceView` is not set.

**Comment by imran87** [comment]
Thanks a lot for reply *Mr* Kishimoto I meant there  have been
written same code in case of ActionSheet or Pop over .Let me give me example if I have
universal app So using your code business logic I will check first iPhone
or iPad. like that

if iPhone { Alertift.actionSheet(message: "Which food do you like?")

   .action(.default("🍣"))
   .action(.default("🍎"))
   .action(.default("🍖"))
   .action(.default("🍅"))
   .action(.cancel("None of them"))
   .finally { action, index in
       if action.style == .cancel {
           return
       }
       Alertift.alert(message: "\(index). \(action.title!)")
           .action(.default("OK"))
           .show()
   }
   .show()

} else { Alertift.actionSheet(message: "Which food do you like?")

   .popover(anchorView: button)
   .action(.default("🍣"))
   .action(.default("🍎"))
   .action(.default("🍖"))
   .action(.default("🍅"))
   .action(.cancel("None of them"))
   .finally { action, index in
       if action.style == .cancel {
           return
       }
       Alertift.alert(message: "\(index). \(action.title!)")
           .action(.default("OK"))
           .show()
   }
   .show()}


So in this way I think repetation of code repeat the same code for iPad
too. So code should manage internally no need to check for iPhone or iPad
If Am I wrong please correct me.

Regards
Imran Khan
(iOS) Software Engineer
+923115106978

**Comment by sgr-ksmt** [comment]
@imran87 

You can write code like below without checking device iPhone or iPad in **universal app**.
The reason why `alertController.popoverPresentationController` is **nil** in case of iPhone. So you may not separate code for `popover(anchorView: button)`.
```swift
// it works both iPhone and iPad without checking.
Alertift.actionSheet(message: "Which food do you like?")
   .popover(anchorView: button) // iPhone: ignored internally, iPad: set anchorView to _alertController.popoverPresentationController
   .action(.default("🍣"))
   .action(.default("🍎"))
   .action(.default("🍖"))
   .action(.default("🍅"))
   .action(.cancel("None of them"))
   .finally { action, index in
       if action.style == .cancel {
           return
       }
       Alertift.alert(message: "\(index). \(action.title!)")
           .action(.default("OK"))
           .show()
   }
   .show()
```

No need `if` statement

```swift
// not good!
if iPhone {
    Alertift.actionSheet(message: "Which food do you like?")
        .action(...)
        .show()
} else {
    Alertift.actionSheet(message: "Which food do you like?")
        .popover(anchorView: button)
        .action(...)
        .show()   
}
```

👍 👍

**Comment by s2imon** [comment]
Hi there, I figured this might be the right place. Is there a way to also customise the color of the 2px line on the alert between the body text and the action text? 
Giving the background black as a color makes the line disappear completely visually. :)

Thanks, I enjoy using this alert library. Very easy to use.

**Comment by imran87** [comment]
Very Good  @Suguru Kishimoto and once again thanks. I like your statement
*"**.popover(anchorView: button) // iPhone: ignored internally, iPad: set
anchorView to".*

So you mean *.popover(anchorView:button) *will be ignored in case of iPhone.

Got It & God bless You.

Regards
Imran Khan
(iOS) Software Engineer
+923115106978
