### ISSUE TITLE
On the cocoapods search less than

### ISSUE THREAD

**Issue by uc43** [sgr-ksmt/Alertift#13]
➜  ~ pod --version
1.2.1
➜  ~ pod search Alertift
[!] Unable to find a pod with name, author, summary, or description matching `Alertift`

**Comment by sgr-ksmt** [comment]
Umm.. I tried searching Alertift and found it.

```
$pod --version
1.2.1

$ pod search Alertift
-> Alertift (1.3)
   UIAlertControlelr wrapper for Swift.
   pod 'Alertift', '~> 1.3'
   - Homepage: https://github.com/sgr-ksmt/Alertift
   - Source:   https://github.com/sgr-ksmt/Alertift.git
   - Versions: 1.3, 1.2, 1.1, 1.0.1, 1.0 [master repo]
```

Also, I can see Alertift on cocoapods.org : https://cocoapods.org/pods/Alertift
