### ISSUE TITLE
Does not work on Swift 4.2

### ISSUE THREAD

**Issue by bennnjamin** [sgr-ksmt/Alertift#29]
Some minor APIs were renamed in Swift 4.2, current version does not compile/run on latest Xcode/Swift. I can make a pull request if you do not have time but the changes are very minor

**Comment by sgr-ksmt** [comment]
Really? I updated Alertift to `v4.0` about 1 month ago.
Please use latest version. if it does not work correctly, plaase inform me or create PR 🙏

**Comment by bennnjamin** [comment]
Yes. Apple renamed some API methods. Maybe 4 lines were affected.

**Comment by ykws** [comment]
@bennnjamin Hi, maybe your version `v3.2`.
I think that I had the same errors, too.
If you like, see #32 .
Best regards!
