### ISSUE TITLE
Add branch tag with SPM

### ISSUE THREAD

**Issue by conversun** [sgr-ksmt/Alertift#41]
![20201029211828-DExqLZ](https://cdn.jsdelivr.net/gh/conversun/statics@master/images/20201029211828-DExqLZ.png)

**Comment by sgr-ksmt** [comment]
@conversun

Oops. I'm sorry about that.
I set `4.2` tag to the latest commit. So could you please retry installing Alertift specifying version `4.2` ?

**Comment by conversun** [comment]
@sgr-ksmt 
Thanks for your reply, But i still can't use..

<img width="726" alt="image" src="https://user-images.githubusercontent.com/22893221/97616534-a228ec80-1a57-11eb-9351-287b44e6b46b.png">

If I manually enter 4.2: 

![20201030023024-R4LHA4](https://cdn.jsdelivr.net/gh/conversun/statics@master/images/20201030023024-R4LHA4.png)

Thanks again 👍

**Comment by sgr-ksmt** [comment]
@conversun Oh... I'm so sorry I made a stupid mistake 😭 
Actually, I should set tag not `4.2` but `4.2.0`.
I marked the latest commit as `4.2.0` and I confirmed I can install `Alertift` via SwiftPM successfully.

<img width="743" alt="Screen Shot 2020-11-02 at 0 53 31" src="https://user-images.githubusercontent.com/9350581/97807731-dc87c900-1ca5-11eb-948b-2352c0dbd27a.png">
<img width="714" alt="Screen Shot 2020-11-02 at 0 53 37" src="https://user-images.githubusercontent.com/9350581/97807733-df82b980-1ca5-11eb-8e0e-869d41a38d0b.png">


Could you please try again? 🙇🏻 🙇🏻 🙇🏻

**Comment by conversun** [comment]
It works, thank you 👍👍👍
